- name: Install Packages
  ansible.builtin.yum:
    name:
      - wget
      - php-mysqlnd
      - php-fpm
      - php-mysqli
      - mariadb105-server
      - php-json
      - php
      - php-devel
      - python
      - python-pip
    state: latest

- name: Install pymysql
  ansible.builtin.pip:
    name: pymysql